version: '3.9'

# great tutorial on getting started with docker compose:
# https://docs.docker.com/compose/gettingstarted/
services:
#  lostify:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - elasticsearch
#
#  elasticsearch:
#    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.15.1'
#    ports:
#      - '9200:9200'
#    environment:
#      - discovery.type=single-node
#    volumes:
#      - elasticsearch:/usr/share/elasticsearch/data

#  kafka + zookeeper configurations:
#  1) doc: https://docs.conduktor.io/kafka-cluster-connection/setting-up-a-connection-to-kafka/connecting-to-kafka-running-under-docker
#  2) (used this one): https://developer.confluent.io/get-started/go/#kafka-setup

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

#volumes:
#  elasticsearch: