version: '3.9'

# great tutorial on getting started with docker compose:
# https://docs.docker.com/compose/gettingstarted/
services:
  lostify:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.15.1'
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

volumes:
  elasticsearch: